implement receive window auto tuning
libp2p/go-yamux pull request #53
Opened 2021-02-22 04:14 UTC by marten-seemann

Fixes #9.

Based on the algorithm used in QUIC: https://docs.google.com/document/d/1F2YfdDXKpy20WVKJueEf4abn_LVZHhMUMS5gX6Pgjl4/edit#heading=h.hcm2y5x4qmqt.

What we do is compare the frequency we're updating the receive window. Updates happen when we've consumed more than half the available. If we're updating more often than once every 2 RTTs, we double the window size (up to a configurable maximum window size).
Unfortunately, we don't have a good way to get an up-to-date RTT measurement here. Instead, we use the ping function to generate an estimate right when we initialize yamux, and use that estimate for the rest of the connection.

2021-02-22 15:29 UTC, willscott commented
```
session_test.go:1237: sendWindow: exp=32768, got=98304
--- FAIL: TestSession_PartialReadWindowUpdate (1.02s)
```

(I didn't look to see if that flakiness was already present.)

2021-02-23 08:22 UTC, marten-seemann commented
@willscott Not really happy with my fix (or the test case as a whole, for that matter), but at least it shouldn't be flaky any more.

2021-02-23 16:10 UTC, willscott approved these changes

2021-02-23 21:51 UTC, Stebalien requested changes

2021-02-24 00:37 UTC, Stebalien commented on util.go
> +func (s *segmentedBuffer) GrowTo(force bool, now time.Time) (bool, uint32) {
This logic doesn't really belong in this type. Can't we compute the target window outside this type and pass it in?

2021-04-12 15:38 UTC, aschmahmann commented
@marten-seemann what's the status of this PR?

2021-04-14 05:01 UTC, marten-seemann commented
@aschmahmann It's in the very unfortunate status of "submitted PR, received review, and totally forgot about it". Sorry for that! I'll clean it up today.

2021-05-05 20:32 UTC, closed without merging