use the resource manager
libp2p/go-yamux pull request #69
Opened 2022-01-05 14:53 UTC by marten-seemann

2022-01-05 14:54 UTC, marten-seemann commented on session.go
> +	s.memoryManager.ReleaseMemory(int(str.recvWindow))
We could use a transactional scope here, but it's easy enough to just release the memory manually.

2022-01-05 14:56 UTC, marten-seemann commented on session.go
> -		delete(s.streams, id)
Note that at this point we haven't inserted the stream into the map yet, so this `delete` was not needed in the first place.

2022-01-05 15:14 UTC, vyzo commented on stream.go
> +			}
wait here we have to release memory back if it is Caution or Critical but the error is nil, as it was actually reserved!

2022-01-11 07:55 UTC, vyzo approved these changes
LGTM

2022-01-11 08:37 UTC, vyzo requested changes
actually wait, as we discussed this is the wrong scope -- it is statically configured, so it is the peer scope by necessity.

2022-01-13 13:10 UTC, vyzo approved these changes

2022-01-17 10:20 UTC, merged